name: Ruby 3.x

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        appraisal:
          - 'google_cloud_tasks_1.0'
          - 'google_cloud_tasks_1.1'
          - 'google_cloud_tasks_1.2'
          - 'google_cloud_tasks_1.3'
          - 'google_cloud_tasks_1.4'
          - 'google_cloud_tasks_1.5'
          - 'google_cloud_tasks_2.0'
          - 'google_cloud_tasks_2.1'
          - 'rails_6.1'
          - 'rails_7.0'
          - 'semantic_logger_3.4'
          - 'semantic_logger_4.6'
          - 'semantic_logger_4.7.0'
          - 'semantic_logger_4.7.2'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.appraisal }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: zhulik/redis-action@1.1.0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
