name: Ruby 2.x

on:
  push:
    branches: [ master, 0.9-stable ]
  pull_request:
    branches: [ master, 0.9-stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.5.9'
          - '2.6.7'
          - '2.7.3'
        appraisal:
          - 'google-cloud-tasks-1.0'
          - 'google-cloud-tasks-1.1'
          - 'google-cloud-tasks-1.2'
          - 'google-cloud-tasks-1.3'
          - 'rails-5.2'
          - 'rails-6.0'
          - 'rails-6.1'
          - 'semantic_logger-3.4'
          - 'semantic_logger-4.6'
          - 'semantic_logger-4.7.0'
          - 'semantic_logger-4.7.2'
    steps:
      - name: Setup System
        run: sudo apt-get install libsqlite3-dev
      - uses: actions/checkout@v2
      - uses: zhulik/redis-action@1.1.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test with Rake
        env:
            APPRAISAL_CONTEXT: ${{ matrix.appraisal }}
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
          bundle exec appraisal ${APPRAISAL_CONTEXT} bundle
          bundle exec appraisal ${APPRAISAL_CONTEXT} rspec
